--- CREATE KUNDE
CREATE TABLE kunde(
  kundennummer NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START WITH 100 INCREMENT BY 10),
  vorname VARCHAR2(255),
  nachname VARCHAR2(255),
  adresse VARCHAR2(255),
  geburtstag DATE,
  PRIMARY KEY(kundennummer)
);

--- CREATE BUCH
CREATE TABLE buch(
  signatur VARCHAR2(255),
  titel VARCHAR2(255),
  bibliothekar NUMBER,
  PRIMARY KEY(signatur),
  FOREIGN KEY(bibliothekar)REFERENCES bibliothekar(personalnummer)
);

DROP TABLE buch;

DROP TABLE kunde;

DROP TABLE buch_kunde;

--- CREATE BIBLIOTHEKAR
CREATE TABLE bibliothekar(
  personalnummer NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START WITH 100 INCREMENT BY 10)PRIMARY KEY,
  vorname VARCHAR2(255),
  nachname VARCHAR2(255)
);

--- CREATE BUCH_KUNDE
CREATE TABLE buch_kunde(
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START WITH 100 INCREMENT BY 10),
  kunde NUMBER,
  buch VARCHAR2(255),
  datum DATE,
  PRIMARY KEY(id),
  FOREIGN KEY(kunde)REFERENCES kunde(kundennummer),
  FOREIGN KEY(buch)REFERENCES buch(signatur)
);

-- Beispiele für die Tabelle "Kunde"
INSERT ALL INTO kunde VALUES(
  101,
  'Anna',
  'Musterfrau',
  'Beispielweg 456, Beispielstadt',
  TO_DATE('05/03/1991', 'DD/MM/YYYY')
)INTO kunde VALUES(
  102,
  'Peter',
  'Schmidt',
  'Testgasse 789, Teststadt',
  TO_DATE('14/10/1995', 'DD/MM/YYYY')
)INTO kunde VALUES(
  103,
  'Sabine',
  'Meier',
  'Musterplatz 987, Musterstadt',
  TO_DATE('08/02/1992', 'DD/MM/YYYY')
)INTO kunde VALUES(
  104,
  'Michael',
  'Huber',
  'Unternehmensallee 321, Unternehmensstadt',
  TO_DATE('15/10/1982', 'DD/MM/YYYY')
)INTO kunde VALUES(
  105,
  'Laura',
  'Wagner',
  'Probenweg 654, Probenstadt',
  TO_DATE('26/04/1973', 'DD/MM/YYYY')
)INTO kunde VALUES(
  106,
  'Thomas',
  'Becker',
  'Musterweg 789, Musterstadt',
  TO_DATE('02/08/1996', 'DD/MM/YYYY')
)INTO kunde VALUES(
  107,
  'Julia',
  'Hofmann',
  'Testplatz 543, Teststadt',
  TO_DATE('17/12/1993', 'DD/MM/YYYY')
)INTO kunde VALUES(
  108,
  'Markus',
  'Schulz',
  'Beispielpfad 876, Beispielstadt',
  TO_DATE('17/09/1987', 'DD/MM/YYYY')
)INTO kunde VALUES(
  109,
  'Sophie',
  'Bauer',
  'Unternehmensstraße 234, Unternehmensstadt',
  TO_DATE('17/04/1979', 'DD/MM/YYYY')
)INTO kunde VALUES(
  110,
  'Max',
  'Mustermann',
  'Musterstraße 123, Musterstadt',
  TO_DATE('17/12/1989', 'DD/MM/YYYY')
)
  SELECT
    1
  FROM
    dual;

-- Beispiele für die Tabelle "Buch"
INSERT ALL INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  'Der Hobbit',
  'H123',
  110
)INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  'Harry Potter und der Stein der Weisen',
  'HP456',
  101
)INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  '1984',
  'N1984',
  102
)INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  'Die Verwandlung',
  'V456',
  103
)INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  'To Kill a Mockingbird',
  'TKM789',
  104
)INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  'Pride and Prejudice',
  'PP123',
  105
)INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  'The Great Gatsby',
  'GG456',
  106
)INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  'Moby-Dick',
  'MD789',
  107
)INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  'Frankenstein',
  'F123',
  108
)INTO buch(
  titel,
  signatur,
  bibliothekar
)VALUES(
  'The Catcher in the Rye',
  'CR456',
  109
)
  SELECT
    1
  FROM
    dual;

-- Beispiele für die Tabelle "Buch_Kunde"
INSERT ALL INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  141,
  101,
  'H123',
  TO_DATE('2023-01-15', 'YYYY-MM-DD')
)INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  142,
  102,
  'HP456',
  TO_DATE('2023-02-20', 'YYYY-MM-DD')
)INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  143,
  103,
  'V456',
  TO_DATE('2023-03-10', 'YYYY-MM-DD')
)INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  144,
  104,
  'TKM789',
  TO_DATE('2023-04-05', 'YYYY-MM-DD')
)INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  145,
  105,
  'PP123',
  TO_DATE('2023-05-12', 'YYYY-MM-DD')
)INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  146,
  106,
  'GG456',
  TO_DATE('2023-06-18', 'YYYY-MM-DD')
)INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  147,
  107,
  'MD789',
  TO_DATE('2023-07-23', 'YYYY-MM-DD')
)INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  148,
  108,
  'F123',
  TO_DATE('2023-08-30', 'YYYY-MM-DD')
)INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  149,
  109,
  'CR456',
  TO_DATE('2023-09-08', 'YYYY-MM-DD')
)INTO buch_kunde(
  id,
  kunde,
  buch,
  datum
)VALUES(
  150,
  110,
  'H123',
  TO_DATE('2023-10-15', 'YYYY-MM-DD')
)
  SELECT
    1
  FROM
    dual;