---------------------------------------------
-- Erstellungsscript f�r die Schul-Datenbank
---------------------------------------------
CREATE TABLE "SDB_LEHRER"(
	"ID" NUMBER,
	"NAME" VARCHAR2(30),
	"VORNAME" VARCHAR2(30),
	"KUERZEL" VARCHAR2(3),
	PRIMARY KEY("ID")
);

CREATE TABLE "SDB_FAECHER"(
	"ID" NUMBER,
	"BEZEICHNUNG" VARCHAR2(50),
	"KUERZEL" VARCHAR2(5),
	PRIMARY KEY("ID")
);

CREATE TABLE "SDB_KLASSEN"(
	"ID" NUMBER,
	"BEZEICHNER" VARCHAR2(5),
	"LEHRERID" NUMBER,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LEHRERID")REFERENCES "SDB_LEHRER"("ID")
);

CREATE TABLE "SDB_SCHUELER"(
	"ID" NUMBER,
	"NAME" VARCHAR2(40),
	"VORNAME" VARCHAR2(40),
	"EMAIL" VARCHAR2(40),
	"KLASSENID" NUMBER,
	PRIMARY KEY("ID"),
	FOREIGN KEY("KLASSENID")REFERENCES "SDB_KLASSEN"("ID")
);

CREATE TABLE "SDB_FAECHERLEHRER"(
	"FACHID" NUMBER,
	"LEHRERID" NUMBER,
	FOREIGN KEY(fachid)REFERENCES sdb_faecher(id),
	FOREIGN KEY(lehrerid)REFERENCES sdb_lehrer(id),
	PRIMARY KEY(fachid, lehrerid)
);

CREATE TABLE "SDB_SCHUELERFAECHERLEHRER"(
	"FACHID" NUMBER,
	"SCHUELERID" NUMBER,
	"LEHRERID" NUMBER,
	"FEHLZEITEN" NUMBER,
	"STUNDENANZAHL" NUMBER,
	FOREIGN KEY(FACHID)REFERENCES SDB_FAECHER(ID),
	FOREIGN KEY(SCHUELERID)REFERENCES SDB_SCHUELER(ID)FOREIGN KEY(LEHRERID)REFERENCES SDB_LEHRER(ID)PRIMARY KEY(SCHUELERID, LEHRERID, FACHID)
);