------------------------------
--* Name   : Steven McGough
--? File   : mitarbeiter.sql
--? Date   : Oct 25, 2023
-- Content: Create Table Artikel and Kunden and insert atributes
------------------------------

CREATE TABLE mitarbeiter(
	personalnummer NUMBER NOT NULL PRIMARY KEY,
	vorname VARCHAR2(50),
	nachname VARCHAR2(50),
	abteilung VARCHAR2(25),
	gehalt NUMBER(8, 2)
);

INSERT ALL INTO mitarbeiter VALUES(
	103,
	'Anna',
	'Müller',
	'Finanzen',
	25000.00
)INTO mitarbeiter VALUES(
	104,
	'Peter',
	'Schmidt',
	'Vertrieb',
	21000.00
)INTO mitarbeiter VALUES(
	105,
	'Lena',
	'Schneider',
	'Marketing',
	23000.00
)INTO mitarbeiter VALUES(
	106,
	'Max',
	'Fischer',
	'IT',
	28000.00
)INTO mitarbeiter VALUES(
	107,
	'Sophie',
	'Schulz',
	'Personal',
	20000.00
)INTO mitarbeiter VALUES(
	108,
	'Felix',
	'Hoffmann',
	'Einkauf',
	22000.00
)INTO mitarbeiter VALUES(
	109,
	'Laura',
	'Wagner',
	'Logistik',
	24000.00
)INTO mitarbeiter VALUES(
	110,
	'David',
	'Becker',
	'Produktion',
	27000.00
)
	SELECT
		1
	FROM
		dual;

SELECT
	*
FROM
	mitarbeiter m;

CREATE TABLE kundenklein(
	kundennummer NUMBER PRIMARY KEY,
	nachname VARCHAR2(50),
	vorname VARCHAR2(50),
	stadt VARCHAR2(25),
	plz NUMBER(5),
	straße VARCHAR2(50),
	hausnummer VARCHAR2(10)
);

INSERT ALL INTO kundenklein VALUES(
	1,
	'Böhmer',
	'Uli',
	'Paderborn',
	'33100',
	'Kaukenberg',
	'5'
)INTO kundenklein VALUES(
	2,
	'Müller',
	'Anna',
	'Berlin',
	'10115',
	'Hauptstraße',
	'12'
)INTO kundenklein VALUES(
	3,
	'Schmidt',
	'Peter',
	'Hamburg',
	'20095',
	'Musterweg',
	'7'
)INTO kundenklein VALUES(
	4,
	'Schneider',
	'Lena',
	'München',
	'80331',
	'Am Park',
	'23'
)INTO kundenklein VALUES(
	5,
	'Fischer',
	'Max',
	'Köln',
	'50667',
	'Domstraße',
	'15'
)INTO kundenklein VALUES(
	6,
	'Schulz',
	'Sophie',
	'Dresden',
	'01067',
	'Altmarkt',
	'8'
)INTO kundenklein VALUES(
	7,
	'Hoffmann',
	'Felix',
	'Stuttgart',
	'70173',
	'Marktplatz',
	'10'
)INTO kundenklein VALUES(
	8,
	'Wagner',
	'Laura',
	'Frankfurt',
	'60313',
	'Kaiserstraße',
	'22'
)INTO kundenklein VALUES(
	9,
	'Becker',
	'David',
	'Hannover',
	'30159',
	'Rathausplatz',
	'14'
)INTO kundenklein VALUES(
	10,
	'Klein',
	'Julia',
	'Düsseldorf',
	'40213',
	'Königsallee',
	'19'
)
	SELECT
		1
	FROM
		dual;

SELECT
	*
FROM
	kundenklein;

DROP TABLE artikel;

CREATE TABLE artikel(
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START WITH 1 INCREMENT BY 1),
	artikelnummer NUMBER,
	bezeichnung VARCHAR2(150),
	beschreibung VARCHAR2(255),
	bestand NUMBER,
	preis NUMBER(8, 2),
	PRIMARY KEY(primary key),
);

INSERT ALL INTO artikel VALUES(
	3231,
	'Käse',
	'würzig, süß',
	30,
	4.99
)INTO artikel VALUES(
	1234,
	'Schokolade',
	'Milchschokolade, 100g',
	50,
	1.99
)INTO artikel VALUES(
	5678,
	'T-Shirt',
	'Blau, Größe M',
	25,
	12.99
)INTO artikel VALUES(
	9876,
	'Kaffee',
	'Gemahlener Kaffee, 250g',
	40,
	6.49
)INTO artikel VALUES(
	5432,
	'Laptop',
	'15-Zoll, 8 GB RAM, 256 GB SSD',
	10,
	799.99
)INTO artikel VALUES(
	1122,
	'Blumenstrauß',
	'Rosen und Lilien, bunt',
	15,
	24.99
)INTO artikel VALUES(
	8765,
	'Buch',
	'Thriller-Roman, Bestseller',
	60,
	9.99
)INTO artikel VALUES(
	2468,
	'Sonnenbrille',
	'Polarisierte Gläser, UV-Schutz',
	35,
	19.99
)INTO artikel VALUES(
	1357,
	'Gartenwerkzeug',
	'Spaten, Rechen, Schaufel',
	20,
	29.99
)INTO artikel VALUES(
	9871,
	'Schuhe',
	'Sneaker, Größe 42, Schwarz',
	40,
	49.99
)
	SELECT
		1
	FROM
		dual;

SELECT
	1
FROM
	dual;

SELECT
	*
FROM
	artikel;